
package com.mycompany.carteleradecine;
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import java.awt.event.*;
import java.time.LocalDate;
import java.time.LocalTime;

public class AdminFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminFrame.class.getName());
    private static final Color AZUL_OSCURO = new Color(13, 27, 62);
    private static final Color AZUL_MEDIO  = new Color(26, 54, 124);
    private static final Color DORADO      = new Color(212, 175, 55);
    private static final Color BLANCO      = Color.WHITE;
    
    private JTextArea areaResultados;
    
    public AdminFrame() {
        initUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new AdminFrame().setVisible(true));
    }

    private void initUI() {
        setTitle("Administrador — " + AppContext.nombreEstado + ", " + AppContext.nombreMunicipio);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 600);
        setLocationRelativeTo(null);
 
        // ── Sidebar izquierdo ──────────────────────────────────────────────────
        JPanel sidebar = new JPanel(new GridBagLayout()) {
            @Override protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g;
                GradientPaint gp = new GradientPaint(0,0,AZUL_OSCURO,0,getHeight(),AZUL_MEDIO);
                g2.setPaint(gp); g2.fillRect(0,0,getWidth(),getHeight());
            }
        };
        sidebar.setPreferredSize(new Dimension(220, 600));
 
        GridBagConstraints s = new GridBagConstraints();
        s.gridx = 0; s.fill = GridBagConstraints.HORIZONTAL; s.weightx = 1.0;
        s.insets = new Insets(4, 10, 4, 10);
 
        JLabel lblTitulo = new JLabel("Administrador");
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 15));
        lblTitulo.setForeground(DORADO);
        lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        s.gridy = 0; s.insets = new Insets(20,10,4,10);
        sidebar.add(lblTitulo, s);
 
        JLabel lblUbic = new JLabel("<html><center><font size='2' color='#aabbcc'>"
            + AppContext.idEstado + " — " + AppContext.idMunicipio + "<br>"
            + AppContext.nombreMunicipio + "</font></center></html>");
        lblUbic.setHorizontalAlignment(SwingConstants.CENTER);
        s.gridy = 1; s.insets = new Insets(0,10,16,10);
        sidebar.add(lblUbic, s);
 
        JSeparator sep = new JSeparator();
        sep.setForeground(new Color(60, 90, 150));
        s.gridy = 2; s.insets = new Insets(0,10,8,10);
        sidebar.add(sep, s);
 
        String[] opciones = {
            "1. Alta de Película","2. Alta de Horario","3. Baja de Película",
            "4. Baja de Horario","5. Modificar Película","6. Consultar Película",
            "7. Consultar Cartelera"
        };
        ActionListener[] acciones = {
            e -> altaPelicula(), e -> altaHorario(), e -> bajaPelicula(),
            e -> bajaHorario(), e -> modificarPelicula(), e -> consultarPelicula(),
            e -> consultarCartelera()
        };
 
        for (int i = 0; i < opciones.length; i++) {
            JButton btn = crearBotonMenu(opciones[i]);
            btn.addActionListener(acciones[i]);
            s.gridy = 3 + i;
            s.insets = new Insets(3, 10, 3, 10);
            sidebar.add(btn, s);
        }
 
        // Botón cerrar sesión
        JButton btnSalir = crearBotonMenu("Cerrar Sesión");
        btnSalir.setForeground(new Color(255, 160, 160));
        btnSalir.addActionListener(e -> {
            new LoginFrame().setVisible(true);
            dispose();
        });
        s.gridy = 3 + opciones.length + 1;
        s.insets = new Insets(20, 10, 10, 10);
        sidebar.add(btnSalir, s);
 
        // Relleno
        JPanel relleno = new JPanel(); relleno.setOpaque(false);
        s.gridy = 99; s.weighty = 1.0;
        sidebar.add(relleno, s);
 
        // ── Panel de resultados derecho ────────────────────────────────────────
        JPanel panelResultados = new JPanel(new BorderLayout());
        panelResultados.setBackground(new Color(248, 250, 255));
 
        JLabel lblArea = new JLabel("  Resultados / Operaciones");
        lblArea.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblArea.setForeground(AZUL_OSCURO);
        lblArea.setBorder(BorderFactory.createMatteBorder(0,0,1,0, new Color(200,210,230)));
        lblArea.setPreferredSize(new Dimension(0, 36));
        panelResultados.add(lblArea, BorderLayout.NORTH);
 
        areaResultados = new JTextArea();
        areaResultados.setFont(new Font("Consolas", Font.PLAIN, 13));
        areaResultados.setEditable(false);
        areaResultados.setBackground(new Color(248, 250, 255));
        areaResultados.setForeground(new Color(30, 40, 60));
        areaResultados.setMargin(new Insets(12, 14, 12, 14));
        areaResultados.setText("Bienvenido al panel de Administrador.\n"
            + "Estado: " + AppContext.nombreEstado + " (" + AppContext.idEstado + ")\n"
            + "Municipio: " + AppContext.nombreMunicipio + " (" + AppContext.idMunicipio + ")\n\n"
            + "Selecciona una operación del menú izquierdo.");
 
        JScrollPane scroll = new JScrollPane(areaResultados);
        scroll.setBorder(null);
        panelResultados.add(scroll, BorderLayout.CENTER);
 
        // ── Layout principal ───────────────────────────────────────────────────
        JSplitPane split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, sidebar, panelResultados);
        split.setDividerLocation(220);
        split.setDividerSize(0);
        split.setBorder(null);
        setContentPane(split);
    }
 
    // ── Operaciones ────────────────────────────────────────────────────────────
 
    private Pelicula buscarPeliculaGlobal(String titulo) {
        for (int i = 0; i < AppContext.listaPeliculas.tamanio(); i++) {
            Pelicula p = AppContext.listaPeliculas.get(i);
            if (p.getTitulo().equalsIgnoreCase(titulo.trim())) {
                return p;
            }
        }
        return null;
    }
    
    private void altaPelicula() {
        JPanel panel = new JPanel(new GridLayout(0, 2, 8, 8));
        JTextField tTitulo    = new JTextField(); JTextField tDirector  = new JTextField();
        JTextField tProductor = new JTextField(); JTextField tClasif    = new JTextField();
        JTextField tDuracion  = new JTextField(); JTextField tGenero    = new JTextField();
        panel.add(new JLabel("Título:")); panel.add(tTitulo);
        panel.add(new JLabel("Director:")); panel.add(tDirector);
        panel.add(new JLabel("Productor:")); panel.add(tProductor);
        panel.add(new JLabel("Clasificación (AA/A/B/B15/C/D):")); panel.add(tClasif);
        panel.add(new JLabel("Duración (min):")); panel.add(tDuracion);
        panel.add(new JLabel("Género:")); panel.add(tGenero);
 
        int r = JOptionPane.showConfirmDialog(this, panel, "Alta de Película", JOptionPane.OK_CANCEL_OPTION);
        if (r != JOptionPane.OK_OPTION) return;
        try {
            int dur = Integer.parseInt(tDuracion.getText().trim());
            Pelicula p = new Pelicula(tTitulo.getText().trim(), tDirector.getText().trim(),
                tProductor.getText().trim(), tClasif.getText().trim(), dur, tGenero.getText().trim());
            AppContext.listaPeliculas.add(p);
            AppContext.pilaDeshacer.push(p);
            mostrar("Película agregada: " + p.getTitulo());
        } catch (Exception ex) {
            mostrar("Error: duración inválida.");
        }
    }
 
    private void altaHorario() {
        String titulo = JOptionPane.showInputDialog(this, "Título de la película:");
        if (titulo == null) return;
        
        // ¡CAMBIO AQUÍ! Usamos el buscador global
        Pelicula p = buscarPeliculaGlobal(titulo);
        if (p == null) { mostrar("Película no encontrada."); return; }

        JPanel panel = new JPanel(new GridLayout(0, 2, 8, 8));
        JTextField tId    = new JTextField(); JTextField tFecha = new JTextField("2026-04-10");
        JTextField tHora  = new JTextField("18:00"); JTextField tSala = new JTextField();
        JTextField tDur   = new JTextField();
        panel.add(new JLabel("ID Horario:")); panel.add(tId);
        panel.add(new JLabel("Fecha (YYYY-MM-DD):")); panel.add(tFecha);
        panel.add(new JLabel("Hora (HH:MM):")); panel.add(tHora);
        panel.add(new JLabel("Sala:")); panel.add(tSala);
        panel.add(new JLabel("Duración (min):")); panel.add(tDur);

        int r = JOptionPane.showConfirmDialog(this, panel, "Alta de Horario — " + p.getTitulo(), JOptionPane.OK_CANCEL_OPTION);
        if (r != JOptionPane.OK_OPTION) return;
        try {
            Horario h = new Horario(Integer.parseInt(tId.getText().trim()),
                LocalDate.parse(tFecha.getText().trim()), LocalTime.parse(tHora.getText().trim()),
                tSala.getText().trim(), Integer.parseInt(tDur.getText().trim()));
            boolean ok = p.agregarHorario(h);
            mostrar(ok ? "Horario agregado a: " + p.getTitulo() : "❌ Empalme de horario detectado.");
        } catch (Exception ex) {
            mostrar("Formato inválido. Use YYYY-MM-DD y HH:MM");
        }
    }
 
    private void bajaPelicula() {
        String titulo = JOptionPane.showInputDialog(this, "Título de la película a eliminar:");
        if (titulo == null) return;
        ListaPeliculas nueva = new ListaPeliculas();
        boolean found = false;
        for (int i = 0; i < AppContext.listaPeliculas.tamanio(); i++) {
            Pelicula p = AppContext.listaPeliculas.get(i);
            if (p.getTitulo().equalsIgnoreCase(titulo.trim())) found = true;
            else nueva.add(p);
        }
        if (found) { AppContext.listaPeliculas = nueva; mostrar("Película eliminada: " + titulo); }
        else mostrar("Película no encontrada.");
    }
 
    private void bajaHorario() {
        String titulo = JOptionPane.showInputDialog(this, "Título de la película:");
        if (titulo == null) return;
        
        // ¡CAMBIO AQUÍ! Usamos el buscador global
        Pelicula p = buscarPeliculaGlobal(titulo);
        if (p == null) { mostrar("Película no encontrada."); return; }

        mostrarHorariosEnArea(p);

        String idStr = JOptionPane.showInputDialog(this, "ID del horario a eliminar:");
        if (idStr == null) return;
        try {
            boolean ok = p.eliminarHorario(Integer.parseInt(idStr.trim()));
            mostrar(ok ? "Horario eliminado." : "ID de horario no encontrado.");
        } catch (Exception ex) { mostrar("ID inválido."); }
    }
 
    private void modificarPelicula() {
        String titulo = JOptionPane.showInputDialog(this, "Título de la película a modificar:");
        if (titulo == null) return;
        
        // ¡CAMBIO AQUÍ! Usamos el buscador global
        Pelicula p = buscarPeliculaGlobal(titulo);
        if (p == null) { mostrar("Película no encontrada."); return; }

        JPanel panel = new JPanel(new GridLayout(0, 2, 8, 8));
        JTextField tTitulo = new JTextField(p.getTitulo());
        JTextField tDir    = new JTextField(p.getDirector());
        JTextField tProd   = new JTextField(p.getProductor());
        JTextField tClasif = new JTextField(p.getClasificacion());
        JTextField tGenero = new JTextField(p.getGenero());
        panel.add(new JLabel("Título:")); panel.add(tTitulo);
        panel.add(new JLabel("Director:")); panel.add(tDir);
        panel.add(new JLabel("Productor:")); panel.add(tProd);
        panel.add(new JLabel("Clasificación:")); panel.add(tClasif);
        panel.add(new JLabel("Género:")); panel.add(tGenero);

        int r = JOptionPane.showConfirmDialog(this, panel, "Modificar — " + p.getTitulo(), JOptionPane.OK_CANCEL_OPTION);
        if (r != JOptionPane.OK_OPTION) return;
        p.setTitulo(tTitulo.getText().trim());
        p.setDirector(tDir.getText().trim());
        p.setProductor(tProd.getText().trim());
        p.setClasificacion(tClasif.getText().trim());
        p.setGenero(tGenero.getText().trim());
        mostrar("Película modificada: " + p.getTitulo());
    }
 
    private void consultarPelicula() {
        String titulo = JOptionPane.showInputDialog(this, "Título a consultar:");
        if (titulo == null) return;
        Pelicula p = buscarPeliculaGlobal(titulo);
        if (p == null) { mostrar("Película no encontrada."); return; }
        
        StringBuilder sb = new StringBuilder();
        sb.append("══ ").append(p.getTitulo()).append(" ══\n");
        sb.append("Director:      ").append(p.getDirector()).append("\n");
        sb.append("Productor:     ").append(p.getProductor()).append("\n");
        sb.append("Clasificación: ").append(p.getClasificacion()).append("\n");
        sb.append("Género:        ").append(p.getGenero()).append("\n");
        sb.append("Duración:      ").append(p.getDuracionMin()).append(" min\n");
        mostrar(sb.toString());
        mostrarHorariosEnArea(p);
    }
 
    private void consultarCartelera() {
        if (AppContext.listaPeliculas.tamanio() == 0) { mostrar("No hay películas en cartelera."); return; }
        StringBuilder sb = new StringBuilder("══ CARTELERA ══\n");
        sb.append("Estado: ").append(AppContext.nombreEstado).append(" | Municipio: ").append(AppContext.nombreMunicipio).append("\n\n");
        for (int i = 0; i < AppContext.listaPeliculas.tamanio(); i++) {
            Pelicula p = AppContext.listaPeliculas.get(i);
            sb.append(i + 1).append(". ").append(p.getTitulo())
              .append("  [").append(p.getClasificacion()).append("]  ").append(p.getGenero()).append("\n");
        }
        mostrar(sb.toString());
    }
 
    private void mostrar(String texto) {
        areaResultados.setText(texto);
    }
 
    private void mostrarHorariosEnArea(Pelicula p) {
        StringBuilder sb = new StringBuilder(areaResultados.getText()).append("\n\n-- Horarios --\n");
        
        // Asumiendo que tu clase Pelicula tiene un método getHorarios() que devuelve la ListaHorarios
        if (p.getHorarios() == null || p.getHorarios().tamanio() == 0) {
            sb.append("No hay horarios registrados.");
        } else {
            for (int i = 0; i < p.getHorarios().tamanio(); i++) {
                Horario h = p.getHorarios().get(i);
                sb.append("Sala: ").append(h.getSala())
                  .append(" | Fecha: ").append(h.getFecha())
                  .append(" | Hora: ").append(h.getHoraInicio()).append("\n");
            }
        }
        areaResultados.setText(sb.toString());
    }
 
    // ── Helpers ────────────────────────────────────────────────────────────────
    private JButton crearBotonMenu(String texto) {
        JButton btn = new JButton(texto);
        btn.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        btn.setForeground(BLANCO);
        btn.setBackground(new Color(35, 65, 130));
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setHorizontalAlignment(SwingConstants.LEFT);
        btn.setOpaque(true);
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn.setBorder(BorderFactory.createEmptyBorder(9, 14, 9, 14));
        btn.addMouseListener(new MouseAdapter() {
            @Override public void mouseEntered(MouseEvent e) { btn.setBackground(new Color(50, 90, 170)); }
            @Override public void mouseExited(MouseEvent e)  { btn.setBackground(new Color(35, 65, 130)); }
        });
        return btn;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
