/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carteleradecine;
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import java.awt.event.*;

public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());
    private static final Color AZUL_OSCURO  = new Color(13, 27, 62);
    private static final Color AZUL_MEDIO   = new Color(26, 54, 124);
    private static final Color DORADO       = new Color(212, 175, 55);
    private static final Color BLANCO       = Color.WHITE;
    private static final Color GRIS_CLARO   = new Color(245, 245, 250);
    private static final Color ROJO_ERROR   = new Color(200, 40, 40);
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblError = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblError.setText("jLabel1");

        btnLogin.setText("jButton1");

        txtPassword.setText("jPasswordField1");

        txtCorreo.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lblError))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnLogin)
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }
    
    private void initUI() {
        setTitle("Cartelera de Cine — Inicio de Sesión");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(480, 520);
        setLocationRelativeTo(null);
        setResizable(false);
 
        // Panel principal con fondo degradado
        JPanel panelPrincipal = new JPanel(new BorderLayout()) {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                GradientPaint gp = new GradientPaint(0, 0, AZUL_OSCURO, 0, getHeight(), AZUL_MEDIO);
                g2.setPaint(gp);
                g2.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        // ── Header ─────────────────────────────────────────────────────────────
        JPanel panelHeader = new JPanel(new GridBagLayout());
        panelHeader.setOpaque(false);
        panelHeader.setBorder(BorderFactory.createEmptyBorder(35, 20, 20, 20));

 
        JLabel lblTitulo = new JLabel("Cartelera de Cine");
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 26));
        lblTitulo.setForeground(DORADO);
        lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);
 
        JLabel lblSub = new JLabel("Inicia sesión para continuar");
        lblSub.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblSub.setForeground(new Color(200, 210, 230));
        lblSub.setHorizontalAlignment(SwingConstants.CENTER);
 
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0; gbc.gridy = 0; gbc.insets = new Insets(0,0,8,0);
        gbc.gridy = 1; gbc.insets = new Insets(0,0,4,0);
        panelHeader.add(lblTitulo, gbc);
        gbc.gridy = 2;
        panelHeader.add(lblSub, gbc);
 
        // ── Tarjeta central ────────────────────────────────────────────────────
        JPanel tarjeta = new JPanel(new GridBagLayout());
        tarjeta.setBackground(BLANCO);
        tarjeta.setBorder(BorderFactory.createCompoundBorder(
            new ShadowBorder(),
            BorderFactory.createEmptyBorder(30, 35, 30, 35)
        ));
 
        GridBagConstraints t = new GridBagConstraints();
        t.fill = GridBagConstraints.HORIZONTAL;
        t.weightx = 1.0;
 
        // Label Correo
        JLabel lblCorreo = crearLabel("Correo electrónico");
        t.gridx = 0; t.gridy = 0; t.insets = new Insets(0,0,6,0);
        tarjeta.add(lblCorreo, t);
 
        // Campo correo
        txtCorreo = crearTextField("correo@ejemplo.com");
        t.gridy = 1; t.insets = new Insets(0,0,18,0);
        tarjeta.add(txtCorreo, t);
 
        // Label Password
        JLabel lblPass = crearLabel("Contraseña");
        t.gridy = 2; t.insets = new Insets(0,0,6,0);
        tarjeta.add(lblPass, t);
 
        // Campo password
        txtPassword = new JPasswordField();
        estilizarCampo(txtPassword);
        t.gridy = 3; t.insets = new Insets(0,0,8,0);
        tarjeta.add(txtPassword, t);
 
        // Label error
        lblError = new JLabel(" ");
        lblError.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lblError.setForeground(ROJO_ERROR);
        lblError.setHorizontalAlignment(SwingConstants.CENTER);
        t.gridy = 4; t.insets = new Insets(0,0,12,0);
        tarjeta.add(lblError, t);
 
        // Botón login
        btnLogin = new JButton("Iniciar Sesión");
        estilizarBoton(btnLogin);
        t.gridy = 5; t.insets = new Insets(0,0,0,0);
        tarjeta.add(btnLogin, t);
 
        // ── Hint de credenciales (para pruebas) ────────────────────────────────
        JLabel lblHint = new JLabel("<html><center><font color='#8899aa' size='2'>"
            + "Admin: " + AppContext.ADMIN_EMAIL + " / " + AppContext.ADMIN_PASS + "<br>"
            + "Cliente: " + AppContext.CLIENT_EMAIL + " / " + AppContext.CLIENT_PASS
            + "</font></center></html>");
        lblHint.setHorizontalAlignment(SwingConstants.CENTER);
 
        // ── Wrap tarjeta ────────────────────────────────────────────────────────
        JPanel wrapTarjeta = new JPanel(new GridBagLayout());
        wrapTarjeta.setOpaque(false);
        wrapTarjeta.setBorder(BorderFactory.createEmptyBorder(0, 40, 0, 40));
        wrapTarjeta.add(tarjeta);
 
        JPanel panelBottom = new JPanel(new BorderLayout());
        panelBottom.setOpaque(false);
        panelBottom.setBorder(BorderFactory.createEmptyBorder(8, 0, 20, 0));
        panelBottom.add(lblHint, BorderLayout.CENTER);
 
        panelPrincipal.add(panelHeader,  BorderLayout.NORTH);
        panelPrincipal.add(wrapTarjeta,  BorderLayout.CENTER);
        panelPrincipal.add(panelBottom,  BorderLayout.SOUTH);
 
        setContentPane(panelPrincipal);
 
        // ── Acciones ────────────────────────────────────────────────────────────
        btnLogin.addActionListener(e -> intentarLogin());
        txtPassword.addActionListener(e -> intentarLogin()); // Enter en password
        txtCorreo.addActionListener(e -> txtPassword.requestFocus());
    }
    
    private void intentarLogin() {
        String correo = txtCorreo.getText().trim().toLowerCase();
        String pass   = new String(txtPassword.getPassword());
 
        if (correo.isEmpty() || pass.isEmpty()) {
            lblError.setText("Por favor completa todos los campos.");
            return;
        }
 
        if (correo.equals(AppContext.ADMIN_EMAIL.toLowerCase()) &&
            pass.equals(AppContext.ADMIN_PASS)) {
            AppContext.rolActual   = "ADMIN";
            AppContext.emailActual = correo;
            abrirUbicacion();
 
        } else if (correo.equals(AppContext.CLIENT_EMAIL.toLowerCase()) &&
                   pass.equals(AppContext.CLIENT_PASS)) {
            AppContext.rolActual   = "CLIENTE";
            AppContext.emailActual = correo;
            abrirUbicacion();
 
        } else {
            lblError.setText("Correo o contraseña incorrectos.");
            txtPassword.setText("");
        }
    }
 
    private void abrirUbicacion() {
        SwingUtilities.invokeLater(() -> {
            UbicacionFrame uf = new UbicacionFrame();
            uf.setVisible(true);
            this.dispose();
        });
    }
    
    
    //estilo 
    private JLabel crearLabel(String texto) {
        JLabel lbl = new JLabel(texto);
        lbl.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lbl.setForeground(new Color(50, 60, 80));
        return lbl;
    }
 
    private JTextField crearTextField(String placeholder) {
        JTextField tf = new JTextField() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (getText().isEmpty() && !isFocusOwner()) {
                    Graphics2D g2 = (Graphics2D) g;
                    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                    g2.setColor(new Color(180, 190, 200));
                    g2.setFont(getFont().deriveFont(Font.ITALIC));
                    Insets ins = getInsets();
                    g2.drawString(placeholder, ins.left + 2, getHeight() / 2 + g2.getFontMetrics().getAscent() / 2 - 2);
                }
            }
        };
        estilizarCampo(tf);
        return tf;
    }
 
    private void estilizarCampo(JComponent campo) {
        campo.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        campo.setPreferredSize(new Dimension(300, 42));
        campo.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(200, 210, 225), 1, true),
            BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        campo.setBackground(GRIS_CLARO);
    }
 
    private void estilizarBoton(JButton btn) {
        btn.setFont(new Font("Segoe UI", Font.BOLD, 15));
        btn.setForeground(AZUL_OSCURO);
        btn.setBackground(DORADO);
        btn.setBorder(BorderFactory.createEmptyBorder(12, 20, 12, 20));
        btn.setFocusPainted(false);
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn.setOpaque(true);
        btn.setBorderPainted(false);
        btn.addMouseListener(new MouseAdapter() {
            @Override public void mouseEntered(MouseEvent e) {
                btn.setBackground(new Color(230, 195, 80));
            }
            @Override public void mouseExited(MouseEvent e) {
                btn.setBackground(DORADO);
            }
        });
    }
 
    //borde con sombra
    static class ShadowBorder extends AbstractBorder {
        private static final int SIZE = 5;
        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int w, int h) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            for (int i = 0; i < SIZE; i++) {
                int alpha = (int)(80 * (1.0 - (double)i / SIZE));
                g2.setColor(new Color(0, 0, 0, alpha));
                g2.drawRoundRect(x + i, y + i, w - i * 2 - 1, h - i * 2 - 1, 14, 14);
            }
            g2.setColor(Color.WHITE);
            g2.fillRoundRect(x + SIZE, y + SIZE, w - SIZE * 2, h - SIZE * 2, 10, 10);
            g2.dispose();
        }
        @Override
        public Insets getBorderInsets(Component c) { return new Insets(SIZE, SIZE, SIZE, SIZE); }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
